### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by NaMlex** [NaMlex/project-planning-demo#1]
**User story**
As a local resident, I want to see a list of upcoming community events.

**Acceptance Criteria**

- [ ] The homepage display a list of upcoming community events.
- [ ] Each event listing includes name, date, time and a brief description.
- [ ] The list is responsive and looks good on all main device sizes.
- [ ] 

**Tasks**

- [ ] Add an HTML section on the homepage dedicated to upcoming community events.
- [ ] Style the event list using Bootstrap.
- [ ] Add some sample events including event name, date, time, and a brief description.
